### ISSUE TITLE
Maximum Framerate

### ISSUE THREAD

**Issue by beniroquai** [openMLA/photon-ultra-controller#1]
Hey @NemoAndrea, great stuff - as always! :) 
May I ask you what would be the maximum framerate you could achieve with this device? I remember you mentioned 2fps for some DMD+Raspi combination, but this may be different since you use a different controlling interface? 
Thanks!:)

**Comment by NemoAndrea** [comment]
With the parallel interface and leaving the DMD to keep exposing (no dark frames), it seems to be handling video playback at 30Hz okay, but I need to do more thorough testing to see if it can actually display all 30 frames. But it looks like video alright.

In theory cranking it to 60Hz should be possible; will give it a shot when I find some time. (need to find something to record images with reliably etc)

**Comment by beniroquai** [comment]
That's awesome! I want one ;D 
The DLP modules from anycubic are available as a spare part or do you need to go through the full teardown everytime you need one? ;-)

**Comment by NemoAndrea** [comment]
eViewTek will (when I asked in january 2024) sell you the optical engine and driver board separately. I was able to get a quote, which was pretty reasonable. I don't know how much stock they have and if they are keeping it in production.

**Comment by NemoAndrea** [comment]
Now in 8-bit :) This should still be ~30Hz

https://github.com/openMLA/photon-ultra-controller/assets/8851596/1073c735-3f78-4d0c-9457-03acd0ee8ca6

**Comment by beniroquai** [comment]
Wow! That is super cool! It's a natural idea to think of using this DMD as the pattern generator for our SIM systems. I'm looking for old Anycubic on Ebay. Maybe I find one that is not that expensive. Impressive! Thanks for sharing. 30 fps is already pretty awesome. One could use the raspi as the trigger device, too, right? 

CC: @ranranking

PS: Wise selection of the Video ;)

**Comment by NemoAndrea** [comment]
Yep, the exposure can be enabled over the software i2c interface of the pi. There is then the option to (1) expose for a certain amount of frames, controlled/intrepreted by the DLPC1438, to (2) to expose until the "STOP EXPOSURE" i2c command is sent. 

So you could leave it in mode (2) and use the framebuffer to switch between expose/stop light/change pattern/light on/expose/ stop light/change pattern/  or (1) and i2c-start->expose->i2c-stop->change pattern->i2c-start->expose. Depends a bit on how problematic the "changing DMD mirror positions" is as it transitions between frames I guess.

**Comment by beniroquai** [comment]
Amazing! Thanks a lot for all the information! I found one on ebay. Potentially broken. Awesome! ^^
